stages:
  data_ingestion:
   cmd: python cnnClassfier/pipeline/stage_01_data_ingestion.py
   deps:
    - cnnClassfier/pipeline/stage_01_data_ingestion.py
    - config/config.yaml
   outs:
    - artifacts/data_ingestion/Chicken-fecal-images


  prepare_base_model:
   cmd: python cnnClassfier\pipeline\stage_02_prepare_base_model.py
   deps:
    - cnnClassfier\pipeline\stage_02_prepare_base_model.py
    - config/config.yaml
   params:
    - IMAGE_SIZE
    - INCLUDE_TOP
    - CLASSES
    - WEIGHTS
    - LEARNING_RATE
   outs:
    -  artifacts\prepare_base_model
  
  training:
   cmd: python cnnClassfier\pipeline\stage_03_training.py
   deps:
    - cnnClassfier\pipeline\stage_03_training.py
    - cnnClassfier\components\prepare_callbacks.py
    - config/config.yaml
    - artifacts\data_ingestion\Chicken-fecal-images
    - artifacts\prepare_base_model
   params:
    - IMAGE_SIZE
    - EPOCHS
    - BATCH_SIZE
    - AUGMENTATION 

   outs:
    - artifacts\training\model.h5 

  evaluation:
   cmd: python cnnClassfier\pipeline\stage_04_evaluation.py
   deps: 
    - cnnClassfier\pipeline\stage_04_evaluation.py
    - config/config.yaml
    - artifacts\data_ingestion\Chicken-fecal-images
    - artifacts\training\model.h5 
   params:
    - BATCH_SIZE
    - IMAGE_SIZE

   metrics:
   - scores.josn:
        cache : false



    
