artifacts_root: artifacts 

#using will help if we need tor eplace new loc we need to update the only in config yaml file 
data_ingestion:
 root_dir: artifacts/data_ingestion
 source_URL: https://github.com/entbappy/Branching-tutorial/blob/master/Chicken-fecal-images.zip
 local_data_file: artifacts/data_ingestion/data.zip
 unzip_dir: artifacts/data_ingestion